version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: product
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: root
      POSTGRES_PASSWORD: product
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
